# Generated by Django 4.2.22 on 2025-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='brochure',
            field=models.FileField(upload_to='static/brochure'),
        ),
    ]
